name: Run Airmiles Script at selected hours

on:
  schedule:
    - cron: '0 7 * * *'    # 09:00 NL
    - cron: '0 8 * * *'    # 10:00 NL
    - cron: '0 9 * * *'    # 11:00 NL
    - cron: '0 10 * * *'   # 12:00 NL
    - cron: '0 11 * * *'   # 13:00 NL
    - cron: '0 12 * * *'   # 14:00 NL
    - cron: '0 13 * * *'   # 15:00 NL
    - cron: '0 14 * * *'   # 16:00 NL
    - cron: '0 15 * * *'   # 17:00 NL
    - cron: '0 16 * * *'   # 18:00 NL
    - cron: '30 16 * * *'  # 18:30 NL
    - cron: '0 17 * * *'   # 19:00 NL
    - cron: '30 17 * * *'  # 19:30 NL
    - cron: '0 18 * * *'   # 20:00 NL
    - cron: '0 19 * * *'   # 21:00 NL
    - cron: '0 20 * * *'   # 22:00 NL
    - cron: '0 21 * * *'   # 23:00 NL
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run Airmiles Script
        run: python airmiles_script.py
