name: Run Airmiles Script every 40 minutes (08:40–22:40 NL tijd)

on:
  schedule:
    - cron: '40 6 * * *'    # 08:40 NL
    - cron: '20 7 * * *'    # 09:20 NL
    - cron: '0 8 * * *'     # 10:00 NL
    - cron: '40 8 * * *'    # 10:40 NL
    - cron: '20 9 * * *'    # 11:20 NL
    - cron: '0 10 * * *'    # 12:00 NL
    - cron: '40 10 * * *'   # 12:40 NL
    - cron: '20 11 * * *'   # 13:20 NL
    - cron: '0 12 * * *'    # 14:00 NL
    - cron: '40 12 * * *'   # 14:40 NL
    - cron: '20 13 * * *'   # 15:20 NL
    - cron: '0 14 * * *'    # 16:00 NL
    - cron: '40 14 * * *'   # 16:40 NL
    - cron: '20 15 * * *'   # 17:20 NL
    - cron: '0 16 * * *'    # 18:00 NL
    - cron: '40 16 * * *'   # 18:40 NL
    - cron: '20 17 * * *'   # 19:20 NL
    - cron: '0 18 * * *'    # 20:00 NL
    - cron: '40 18 * * *'   # 20:40 NL
    - cron: '20 19 * * *'   # 21:20 NL
    - cron: '0 20 * * *'    # 22:00 NL
    - cron: '40 20 * * *'   # 22:40 NL
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run Airmiles Script
        run: python airmiles_script.py
